### ISSUE TITLE
Generating a new unique userid - automatically disable option in settings for next launch?

### ISSUE THREAD

**Issue by mantazzo** [Detanup01/Goldberg_r2_extended#2]
The new unique userid generation is great, however, from our testing, it seems that a new ID is generated on every launch, which means that some games keep creating new data - in our test with another person, we tested TM2020 and on every launch when a new ID is generated, all settings and records are lost.

**Suggestion**
If possible, make it so that when a new userID is generated, it would be saved to the ini file and the generation option would be disabled. That would probably be a lot more convenient for everyone.

Thanks for the recent update.

**Comment by Detanup01** [comment]
hey, sorry for loong wait, fixed it.
